name: Update from Upstream

on:
  schedule:
    - cron: '55 13 * * *' # Atur jadwal sesuai kebutuhan

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Add upstream remote
      run: git remote add upstream 

    - name: Fetch upstream changes
      run: git fetch upstream https://github.com/sandhikagalih/project-kalian/tree/season-3

    - name: Merge upstream into your branch
      run: git merge upstream/main # Gantilah 'main' dengan nama branch Anda

    - name: Push changes to your fork
      run: git push origin main # Gantilah 'main' dengan nama branch Anda
